#ifndef _DATAGRAMS_
#define _DATAGRAMS_

// Users Datagrams Errors
#define DGE_HANDLE_IS_ILLEGAL       "E01" // unused (see: E7)
#define DGE_HANDLE_UNAVAILABLE      "E02"
#define DGE_HANDLE_RESERVED         "E03"
#define DGE_WRONG_PASSWORD          "E04"
#define DGE_HANDLE_TOO_SHORT        "E05"
#define DGE_HANDLE_TOO_LONG         "E06"
#define DGE_HANDLE_ILLEGAL_CHAR     "E07"
#define DGE_PASSWORD_TOO_SHORT      "E08"
#define DGE_PASSWORD_TOO_LONG       "E09"
#define DGE_PASSWORD_DONT_MATCH     "E10"
#define DGE_HANDLE_NOT_REGISTERED   "E11"
#define DGE_AUTO_LOGOUT_IDLENESS    "E12"
#define DGE_UNKNOWN_COMMAND         "E13"
#define DGE_SERVER_SHUTOFF          "E14"
#define DGE_SERVER_SHUTDOWN         "E15"
#define DGE_PLAYER_RECONNECT        "E16"
#define DGE_PLAYER_LOAD_FAILED      "E17"
#define DGE_SOCKET_FLOOD            "E18"
#define DGE_PLAYER_AT_TABLE         "E19"
#define DGE_PLAYER_NO_TABLE         "E20"
#define DGE_TABLE_WRONG_CHAIR       "E21"
#define DGE_PLAYER_SIT_DELAY        "E22"
#define DGE_SOCKET_MAX_CONN_IP      "E23"
#define DGE_TABLE_NOT_FOUND         "E24"
#define DGE_AMBIGOUS_COMMAND        "E25"
#define DGE_TABLE_MUTED             "E26"
#define DGE_PLAYER_NOT_SAT          "E27"
#define DGE_TABLE_NOT_3PASSED       "E28"
#define DGE_TABLE_ALREADY_PASSED    "E29"
#define DGE_TABLE_ILLEGAL_CARD      "E30"
#define DGE_TABLE_CARD_NOT_FOUND    "E31"
#define DGE_TABLE_DOUBLE_CARD       "E32"
#define DGE_TABLE_PASSING_OVER      "E33"
#define DGE_TABLE_STARTED           "E34"
#define DGE_TABLE_FULL              "E35"
#define DGE_TABLE_NOT_STARTED       "E36"
#define DGE_TABLE_NOT_YOUR_TURN     "E37"
#define DGE_TABLE_CANT_BREAK_HEART  "E38"
#define DGE_TABLE_QUEEN_SPADE       "E39"
#define DGE_TABLE_WRONG_SUIT        "E40"
#define DGE_SOCKET_MAX_REGISTER_IP  "E41"
#define DGE_TABLE_ALREADY_PLAYED    "E42"
#define DGE_SOCKET_ILLEGAL_INPUT    "E43"
#define DGE_PLAYER_NOT_MOON         "E44"
#define DGE_COMMAND_WRONG_PARAMETER "E45"
#define DGE_ADMIN_NOT_FOUND         "E46"
#define DGE_ADMIN_ABOVE             "E47"
#define DGE_TABLE_CORRUPTED         "E48"
#define DGE_WRONG_VALUE             "E49"

// Users datagrams Informations
#define DGI_PLAYER_UID              "I01"
#define DGI_PLAYER_CHOOSE_CHAIR     "I02"
#define DGI_PLAYER_SIT_HERE         "I03"
#define DGI_PLAYER_STAND            "I04"
#define DGI_TABLE_CREATED           "I05"
#define DGI_TABLE_DELETED           "I06"
#define DGI_TABLE_SAY               "I07"
#define DGI_TABLE_YOUR_CARDS        "I08"
#define DGI_TABLE_YOUR_TURN         "I09"
//#define DGI_SERVER_WHO              "I10"  // unused, using DG_TEXT now
#define DGI_TABLE_LEAVE             "I11"
#define DGI_TABLE_CARDS_RECEIVED    "I12"
#define DGI_TABLE_FORCE_PASS        "I13"
#define DGI_TABLE_FORCE_PLAY        "I14"
#define DGI_TABLE_PLAY_TWO_CLUBS    "I15"
#define DGI_TABLE_PLAY              "I16"
#define DGI_TABLE_HAND_SCORE        "I17"
#define DGI_TABLE_SCORE             "I18"
#define DGI_TABLE_WHO_AM_I          "I19"
#define DGI_TABLE_NO_TRICK_BONUS    "I20"
#define DGI_TABLE_OMNIBUS           "I21"
#define DGI_TABLE_PERFECT_100       "I22"
#define DGI_TABLE_SHOOT_MOON        "I23"
#define DGI_COMMAND_SET             "I24"
#define DGI_TABLE_GAMEOVER          "I25"
#define DGI_TABLE_PAUSED            "I26"
#define DGI_TABLE_UNPAUSED          "I27"
#define DGI_SERVER_ANNOUNCE         "I28"
#define DGI_PLAYER_MOON             "I29"
#define DGI_TABLE_CLEAR             "I30"
#define DGI_ADMIN_SET               "I31"
#define DGI_TABLE_SHUFFLE           "I32"
#define DGI_GAME_STATS              "I33"
#define DGI_PLAYER_NEW_PASSWORD     "I34"
#define DGI_GAME_STARTED            "I35"
#define DGI_TEXT                    "I36"
#define DGI_RECONNECTED             "I37"

// Users Datagrams help commands informations
#define DGH_HELP_DATE               "H01"
#define DGH_HELP_EXIT               "H02"
#define DGH_HELP_HELP               "H03"
#define DGH_HELP_JOIN               "H04"
#define DGH_HELP_LEAVE              "H05"
#define DGH_HELP_MOON               "H06"
#define DGH_HELP_MUTE               "H07"
#define DGH_HELP_NEW                "H08"
#define DGH_HELP_PASS               "H09"
#define DGH_HELP_PASSWORD           "H10"
#define DGH_HELP_PLAY               "H11"
#define DGH_HELP_SAY                "H12"
#define DGH_HELP_SIT                "H13"
#define DGH_HELP_STATS              "H14"
#define DGH_HELP_TABLES             "H15"
#define DGH_HELP_UPTIME             "H16"
#define DGH_HELP_WHO                "H17"

// Admin Datagrams help commands informations
#define DGH_HELP_ADMIN              "H50"
#define DGH_HELP_ANNOUNCE           "H51"
#define DGH_HELP_PAUSE              "H52"
#define DGH_HELP_SET                "H53"
#define DGH_HELP_SHUTDOWN           "H54"
#define DGH_HELP_SHUTOFF            "H55"
#define DGH_HELP_TEST               "H56"

#endif // _DATAGRAMS_
