#ifndef ERRORS
#define ERRORS

#define HANDLE_IS_ILLEGAL     "E01" // unused (see: E7)
#define HANDLE_UNAVAILABLE    "E02"
#define HANDLE_RESERVED       "E03"
#define WRONG_PASSWORD        "E04"
#define HANDLE_TOO_SHORT      "E05"
#define HANDLE_TOO_LONG       "E06"
#define HANDLE_ILLEGAL_CHAR   "E07"
#define PASSWORD_TOO_SHORT    "E08"
#define PASSWORD_TOO_LONG     "E09"
#define PASSWORD_DONT_MATCH   "E10"
#define HANDLE_NOT_REGISTERED "E11"
#define AUTO_LOGOUT_IDLENESS  "E12"
#define UNKNOWN_COMMAND       "E13"
#define SERVER_SHUTOFF        "E14"
#define SERVER_SHUTDOWN       "E15"
#define PLAYER_RECONNECT      "E16"
#define PLAYER_LOAD_FAILED    "E17"
#define SOCKET_FLOOD          "E18"
#define PLAYER_AT_TABLE       "E19"
#define PLAYER_NO_TABLE       "E20"
#define TABLE_WRONG_CHAIR     "E21"
#define PLAYER_SIT_DELAY      "E22"
#define SOCKET_MAX_CONN_IP    "E23"
#define TABLE_NOT_FOUND       "E24"
#define AMBIGOUS_COMMAND      "E25"
#define TABLE_MUTED           "E26"
#define PLAYER_NOT_SAT        "E27"
#define TABLE_NOT_3PASSED     "E28"
#define TABLE_ALREADY_PASSED  "E29"
#define TABLE_ILLEGAL_CARD    "E30"
#define TABLE_CARD_NOT_FOUND  "E31"
#define TABLE_DOUBLE_CARD     "E32"
#define TABLE_PASSING_OVER    "E33"
#define TABLE_STARTED         "E34"
#define TABLE_FULL            "E35"

#define PLAYER_UID            "I01"
#define PLAYER_CHOOSE_CHAIR   "I02"
#define PLAYER_SIT_HERE       "I03"
#define PLAYER_STAND          "I04"
#define TABLE_CREATED         "I05"
#define TABLE_DELETED         "I06"
#define TABLE_SAY             "I07"
#define TABLE_YOUR_CARDS      "I08"
#define TABLE_YOUR_TURN       "I09"
#define SERVER_WHO            "I10"
#define TABLE_LEAVE           "I11"
#define TABLE_CARDS_RECEIVED  "I12"
#define TABLE_FORCE_PASS      "I13"

#endif
