#ifndef ERRORS
#define ERRORS

#define HANDLE_IS_ILLEGAL     "E1" // unused (see: E7)
#define HANDLE_UNAVAILABLE    "E2"
#define HANDLE_RESERVED       "E3"
#define WRONG_PASSWORD        "E4"
#define HANDLE_TOO_SHORT      "E5"
#define HANDLE_TOO_LONG       "E6"
#define HANDLE_ILLEGAL_CHAR   "E7"
#define PASSWORD_TOO_SHORT    "E8"
#define PASSWORD_TOO_LONG     "E9"
#define PASSWORD_DONT_MATCH   "E10"
#define HANDLE_NOT_REGISTERED "E11"
#define AUTO_LOGOUT_IDLENESS  "E12"
#define UNKNOWN_COMMAND       "E13"
#define SERVER_SHUTOFF        "E14"
#define SERVER_SHUTDOWN       "E15"
#define PLAYER_RECONNECT      "E16"
#define PLAYER_LOAD_FAILED    "E17"
#define SOCKET_FLOOD          "E18"
#define PLAYER_AT_TABLE       "E19"
#define PLAYER_NO_TABLE       "E20"
#define TABLE_WRONG_CHAIR     "E21"
#define PLAYER_SIT_DELAY      "E22"
#define SOCKET_MAX_CONN_IP    "E23"
#define TABLE_NOT_FOUND       "E24"
#define AMBIGOUS_COMMAND      "E25"
#define TABLE_MUTED           "E26"
#define PLAYER_NOT_SAT        "E27"

#define PLAYER_UID            "I1"
#define PLAYER_CHOOSE_CHAIR   "I2"
#define PLAYER_SIT_HERE       "I3"
#define PLAYER_STAND          "I4"
#define TABLE_CREATED         "I5"
#define TABLE_DELETED         "I6"
#define TABLE_SAY             "I7"
#define TABLE_YOUR_CARDS      "I8"
#define TABLE_YOUR_TURN       "I9"
#endif
